services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-form-acolher
    ports:
      - "88:80"
    networks:
      - react_network
networks:
  react_network:
