version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-form-acolher
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt        # Volume para os certificados
      - ./data/certbot/www:/var/www/certbot         # Volume para validação do Certbot
    env_file: 
      - .env.production
    networks:
      - react_network
      - formulario-cadastro

networks:
  react_network:
  formulario-cadastro:
    external: true
