
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-form-acolher
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    env_file: 
      - .env.production  # Carregue o arquivo .env.production explicitamente
    networks:
      - react_network
      - formulario-cadastro

networks:
  react_network:
  formulario-cadastro:
    external: true
