services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-form-acolher
    ports:
      - "${REACT_APP_PORT}:3000"  # Usa a variável de ambiente para a porta
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    networks:
      - react_network
      - formulario-cadastro
