services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-form-acolher
    ports:
      - "${REACT_APP_PORT}:3000"  # Usa uma variável de ambiente para a porta
    networks:
      - react_network
      - formulario-cadastro

networks:
  react_network:
  formulario-cadastro:
    external: true
