version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-form-acolher
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt         # Volume para certificados
      - ./data/certbot/www:/var/www/certbot          # Volume para validação do Certbot
    networks:
      - react_network
      - formulario-cadastro

 certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/www:/var/www/certbot          # Volume para validação do Certbot
      - ./data/certbot/conf:/etc/letsencrypt 
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'"

networks:
  react_network:
  formulario-cadastro:
    external: true
