services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-form-acolher
    ports:
      - "443:80"
    networks:
      - react_network
      - formulario-cadastro  # Conecta à rede externa

networks:
  react_network:
  formulario-cadastro:
    external: true  # Declara que a rede já existe
